[package]
name = "fo_lst_format"
version = "0.1.0"
authors = ["qthree <qthree3@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom_prelude = { git = "https://github.com/fonline-rust/format_extras.git" }
